services:

  site:
    container_name: blog
    image: php:8.2-apache
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/html

  db:
    container_name: db
    image: mysql:8.0
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes: 
      - ./db:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    ports:
      - 8081:80
     



volumes:
  src:
  db:
